# NumPy

* Numerical Python의 약자

* 다양한 수학 연산과 다차원 데이터를 쉽게 다루기 위한 파이썬 라이브러리

* Numpy는 ndarray라고 하는 특별한 객체를 사용
    + 리스트와 달리 고정된 크기를 갖음
    + 같은 타입의 데이터만 저장 가능

* ndarray는 python 리스트에서 지원하지 않는 다양한 기능들을 지원
    + 효율적으로 코드 작성 가능
    + 더 빠른 속도

In [70]:
!pip install numpy

In [2]:
import numpy as np
np.__version__

'1.19.5'



---



# 배열 생성

## 리스트로 배열 만들기
![1.2 Array.png](https://drive.google.com/uc?id=1EKPVGuDQinETf6XkcKFYaQfqp5P2oklE)

In [3]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3


In [4]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print(type(a2))
print(a2.shape)
print(a2[0, 0], a2[1, 1])

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
1 5


In [5]:
a3 = np.array([[[1, 2, 3, 4], [4, 5, 6, 7], [9, 0 , 1, 2]],
               [[3, 4, 5, 6], [7, 8 ,9, 0], [1, 2, 3, 4]]])
print(a3)
print(a3.shape)

[[[1 2 3 4]
  [4 5 6 7]
  [9 0 1 2]]

 [[3 4 5 6]
  [7 8 9 0]
  [1 2 3 4]]]
(2, 3, 4)


## 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [7]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [8]:
np.full((2, 3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [10]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [11]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [12]:
print(a1)
np.zeros_like(a1)

[1 2 3 4 5]


array([0, 0, 0, 0, 0])

In [13]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]]


array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3 4]
  [4 5 6 7]
  [9 0 1 2]]

 [[3 4 5 6]
  [7 8 9 0]
  [1 2 3 4]]]


array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

## 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [15]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [16]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## 랜덤값으로 배열 생성

| 함수 | 설명 |
|------|------|
| `seed` | 난수 발생을 위한 시드(seed) 지정 |
| `permutation` | 순서를 임의로 바꾸거나 임의의 순열 반환 |
| `shuffle` | 리스트나 배열의 순서를 뒤섞음 |
| `random` | 랜덤한 수의 배열 생성 |
| `rand` | 균등분포에서 표본 추출 |
| `randint` | 주어진 최소/최대 범위의 난수 추출 |
| `randn` | 표준편차가 1, 평균값 0인 정규분포의 표본 추출 |
| `binomial` | 이항분포에서 표본 추출 |
| `normal` | 정규분포(가우시안)에서 표본 추출 |
| `beta` | 베타분포에서 표본 추출 |
| `chisquare` | 카이제곱분포에서 표본 추출 |
| `gamma` | 감마분포에서 표본 추출 |
| `uniform` | 균등(0, 1)분포에서 표본 추출 |

* `random.random()`: 랜덤한 수의 배열 생성

In [17]:
np.random.random((3, 3))

array([[0.75775605, 0.42146794, 0.96734908],
       [0.42706887, 0.79795592, 0.18479153],
       [0.23201566, 0.77573692, 0.34375015]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [18]:
np.random.randint(0, 10, (3, 3))

array([[8, 9, 1],
       [5, 4, 6],
       [4, 7, 1]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [19]:
np.random.normal(0, 1, (3, 3))

array([[ 1.52173115,  0.70555187,  0.58224713],
       [ 1.15112198, -0.11930602,  0.06817123],
       [ 0.19131934, -0.08630302, -0.45826731]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [20]:
np.random.rand(3, 3)

array([[0.15241715, 0.03793346, 0.79776152],
       [0.30736308, 0.71257885, 0.25892649],
       [0.08531414, 0.64556656, 0.83022492]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [21]:
np.random.randn(3, 3)

array([[-0.41151502, -1.10172544, -0.04218077],
       [ 0.84061905,  0.58197563, -0.59409171],
       [ 0.16882397, -2.06203487, -1.10352456]])

## 표준 데이터 타입

| 데이터 타입	    | 설명 |
|---------------|-------------|
| ``bool_``     | 바이트로 저장된 불리언(Boolean)으로 True 또는 False 값을 가짐 |
| ``int_``      | 기본 정수(Integer) 타입 | 
| ``intc``      | C 언어에서 사용되는 ``int``와 동일 (일반적으로 ``int32`` 또는 ``int64``) | 
| ``intp``      | 인덱싱에 사용되는 정수 (C 언어에서 ``ssize_t``와 동일; 일반적으로 ``int32`` 또는 ``int64``) | 
| ``int8``      | 바이트(Byte) (-128 ~ 127) | 
| ``int16``     | 정수 (-32768 ~ 32767) |
| ``int32``     | 정수 (-2147483648 ~ 2147483647) |
| ``int64``     | 정수(-9223372036854775808 ~ 9223372036854775807) | 
| ``uint8``     | 부호 없는 정수 (0 ~ 255) | 
| ``uint16``    | 부호 없는 정수 (0 ~ 65535) | 
| ``uint32``    | 부호 없는 정수 (0 ~ 4294967295) | 
| ``uint64``    | 부호 없는 정수 (0 ~ 18446744073709551615) |  
| ``float16``   | 반정밀 부동 소수점(Half precision float): 부호 비트, 5비트 지수, 10비트 가수 | 
| ``float32``   | 단정밀 부동 소수점(Single precision float): 부호 비트, 8비트 지수, 23비트 가수| 
| ``float64``   | 배정밀 부동 소수점(Double precision float): 부호 비트, 11비트 지수, 52비트 가수 |
| ``float_``    | ``float64``를 줄여서 표현 |
| ``complex64`` | 복소수(Complex number), 두 개의 32비트 부동 소수점으로 표현 | 
| ``complex128``| 복소수, 두 개의 64비트 부동 소수점으로 표현| 
| ``complex_``  | ``complex128``를 줄여서 표현 | 

In [22]:
np.zeros(20, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((3, 3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [24]:
np.full((3, 3), 1, dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])



---



# 배열 조회

## 배열 속성 정보

In [25]:
def array_info(array):
    print(array)
    print("ndim :", array.ndim)
    print("shape :", array.shape)
    print("dtype :", array.dtype)
    print("size :", array.size)
    print("itemsize :", array.itemsize)
    print("nbytes :", array.nbytes)
    print("strides :", array.strides)

In [26]:
array_info(a1)

[1 2 3 4 5]
ndim : 1
shape : (5,)
dtype : int32
size : 5
itemsize : 4
nbytes : 20
strides : (4,)


In [27]:
array_info(a2)

[[1 2 3]
 [4 5 6]]
ndim : 2
shape : (2, 3)
dtype : int32
size : 6
itemsize : 4
nbytes : 24
strides : (12, 4)


In [28]:
array_info(a3)

[[[1 2 3 4]
  [4 5 6 7]
  [9 0 1 2]]

 [[3 4 5 6]
  [7 8 9 0]
  [1 2 3 4]]]
ndim : 3
shape : (2, 3, 4)
dtype : int32
size : 24
itemsize : 4
nbytes : 96
strides : (48, 16, 4)


## 인덱싱(Indexing)

In [29]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[1 2 3 4 5]
1
3
5
4


In [30]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, -1])

[[1 2 3]
 [4 5 6]]
1
3
6


In [31]:
print(a3)
print(a3[0, 0, 0])
print(a3[1, 1, 1])
print(a3[0, -1, -1])

[[[1 2 3 4]
  [4 5 6 7]
  [9 0 1 2]]

 [[3 4 5 6]
  [7 8 9 0]
  [1 2 3 4]]]
1
8
2


## 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [32]:
print(a1)
print(a1[0:2])
print(a1[1:])
print(a1[:3])
print(a1[::2])
print(a1[::-1])

[1 2 3 4 5]
[1 2]
[2 3 4 5]
[1 2 3]
[1 3 5]
[5 4 3 2 1]


In [33]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:1, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]]
[4 5 6]
[4 5 6]
[[1 2]]
[[6 5 4]]
[[4 5 6]
 [1 2 3]]
[[6 5 4]
 [3 2 1]]


## 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [34]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
bi = [True, False, True, True, False]
print(a1[bi])

[1 2 3 4 5]
[2 3 5]
[1 3 4]


In [35]:
print(a2)
bi = np.random.randint(0, 2, (2, 3), dtype = bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]]
[[False False False]
 [False False False]]
[]




---



# 배열 값 삽입/수정/삭제/복사

## 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [36]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
c1 = np.insert(a1, 2, 10)
print(c1)

[1 2 3 4 5]
[10  1  2  3  4  5]
[ 1  2 10  3  4  5]


In [37]:
print(a2)
b2 = np.insert(a2, 1, 10, axis = 0)
print(b2)
c2 = np.insert(a2, 1, 10, axis = 1)
print(c2)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]]
[[ 1 10  2  3]
 [ 4 10  5  6]]


## 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [38]:
a1[0] = 11
a1[1] = 22
a1[2] = 33
print(a1)

[11 22 33  4  5]


In [39]:
a1[:2] = 9
print(a1)

[ 9  9 33  4  5]


In [40]:
i = np.array([1, 3, 4])
a1[i] = 0
print(a1)

[ 9  0 33  0  0]


In [41]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
a2[0, 0] = 11
a2[1, 1] = 22
print(a2)

[[11  2  3]
 [ 4 22  6]
 [ 7  8  9]]


In [43]:
a2[0] = 1
print(a2)

[[ 1  1  1]
 [ 4 22  6]
 [ 7  8  9]]


In [44]:
a2[1:, 2] = 19
print(a2)

[[ 1  1  1]
 [ 4 22 19]
 [ 7  8 19]]


## 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [45]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)

[1 2 3 4 5]


In [46]:
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[1 3 4 5]
[1 2 3 4 5]


In [47]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
b2 = np.delete(a2, 1, axis = 0)
print(b2)

[[1 2 3]
 [7 8 9]]


In [49]:
c2 = np.delete(a2, 1, axis = 1)
print(c2)

[[1 3]
 [4 6]
 [7 9]]


## 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [50]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
a2_sub = a2[:2, :2]
print(a2_sub)

[[1 2]
 [4 5]]


In [52]:
a2_sub[:, 1] = 0
print(a2_sub)
print(a2)

[[1 0]
 [4 0]]
[[1 0 3]
 [4 0 6]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [53]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)

[[1 2]
 [4 5]]


In [55]:
a2_sub_copy[:, 1] = 0
print(a2_sub_copy)
print(a2)

[[1 0]
 [4 0]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]




---



# 배열 변환

## 배열 전치 및 축 변경

In [56]:
print(a2.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [57]:
print(a2.swapaxes(1, 0))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [58]:
n1 = np.arange(1, 10)
print(n1)

print(n1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가. 한 차원 증가

In [59]:
print(n1)

[1 2 3 4 5 6 7 8 9]


In [60]:
print(n1[np.newaxis, 2:5])

print(n1[2:5, np.newaxis])

[[3 4 5]]
[[3]
 [4]
 [5]]


## 배열 크기 변경

* `resize()`: 배열 크기 변경
* element의 수가 같으면, 배열 모양만 변경
* element의 sequence는 유지됨

In [61]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)

[[2 4 7 6 2]
 [9 7 1 7 5]]


In [62]:
n2.resize((5, 2))
print(n2)

[[2 4]
 [7 6]
 [2 9]
 [7 1]
 [7 5]]


* resize 크기가 원본 배열보다 크면, 남은 공간은 0으로 채워짐

In [63]:
n2.resize((5, 5))
print(n2)

[[2 4 7 6 2]
 [9 7 1 7 5]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [64]:
np.resize(n2, (5, 5))

array([[2, 4, 7, 6, 2],
       [9, 7, 1, 7, 5],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

* resize 크기가 원본 배열보다 작으면, 기본 값은 삭제됨

In [65]:
n2.resize((3, 3))
print(n2)

[[2 4 7]
 [6 2 9]
 [7 1 7]]


## 배열 추가

* `append()`: 배열의 끝에 값 추가

In [66]:
a2 = np.arange(1, 10).reshape(3, 3)
b2 = np.arange(10, 19).reshape(3, 3)
print(a2)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [67]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정 : 행 방향 결합

In [68]:
c2 = np.append(a2, b2, axis = 0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정 : 열 방향 결합

In [69]:
c2 = np.append(a2, b2, axis = 1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


## 배열 분할

* `split()`: 배열 분할

In [70]:
a1 = np.arange(11, 21)
print(a1)

[11 12 13 14 15 16 17 18 19 20]


In [71]:
b1, c1 = np.split(a1, [5])
print(b1, c1)

[11 12 13 14 15] [16 17 18 19 20]


In [72]:
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[11 12] [13 14] [15 16] [17 18] [19 20]


* `vsplit()`: 수직(y축) 분할. 행 분할

In [73]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [74]:
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평(x축) 분할. 열 분할

In [75]:
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]




---



# 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

## 브로드캐스팅(Broadcasting)

![1.3 Broadcasting.png](https://drive.google.com/uc?id=1iDTSzbR5GILf1-A7aTfNssG_IF6UZAD2)

In [76]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1 + 5)

[1 2 3]
[6 7 8]


In [77]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
print(a1 + a2)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [79]:
b2 = np.array([1, 2, 3]).reshape(3, 1)
print(b2)

[[1]
 [2]
 [3]]


In [80]:
print(a1 + b2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


## 산술 연산(Arithmetic Operators)

| 연산자	      | 범용 함수           | 설명        |
|---------------|---------------------|-------------|
|``+``          |``np.add``           | 덧셈        |
|``-``          |``np.subtract``      | 뺄셈        |
|``-``          |``np.negative``      | 단항 음수  |
|``*``          |``np.multiply``      | 곱셈        |
|``/``          |``np.divide``        | 나눗셈      |
|``//``         |``np.floor_divide``  | 나눗셈 내림 |
|``**``         |``np.power``         | 지수 연산   |
|``%``          |``np.mod``           | 나머지 연산 |


In [81]:
a1 = np.arange(1, 10)
print(a1)

[1 2 3 4 5 6 7 8 9]


In [82]:
print(a1 + 1)
print(np.add(a1, 10))

[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]


In [83]:
a1 = np.arange(1, 10)
b1 = np.random.randint(1, 10, size = 9)
print(a1)
print(b1)

[1 2 3 4 5 6 7 8 9]
[3 1 8 1 3 7 9 2 5]


In [84]:
print(a1 + b1)
print(np.add(a1, b1))

[ 4  3 11  5  8 13 16 10 14]
[ 4  3 11  5  8 13 16 10 14]


## 절대값 함수

In [88]:
a1 = np.random.randint(-10, 10, size = 5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[-2  9  0 -8 -2]
[2 9 0 8 2]
[2 9 0 8 2]


- square, sqrt : 제곱, 제곱근 함수

In [91]:
# 제곱/제곱근 함수

print(np.square(a1))
print(np.sqrt(a1))

[ 4 81  0 64  4]
[nan  3.  0. nan nan]


<ipython-input-91-512c423042f2>:4: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


In [92]:
# 지수와 로그함수

a1 = np.random.randint(1, 10, size = 5)
print(a1)
print(np.exp(a1))
print(np.exp(a1))
print(np.power(a1, 2))

[5 7 1 6 7]
[ 148.4131591  1096.63315843    2.71828183  403.42879349 1096.63315843]
[ 148.4131591  1096.63315843    2.71828183  403.42879349 1096.63315843]
[25 49  1 36 49]


In [93]:
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[1.60943791 1.94591015 0.         1.79175947 1.94591015]
[2.32192809 2.80735492 0.         2.5849625  2.80735492]
[0.69897    0.84509804 0.         0.77815125 0.84509804]


In [95]:
a2 = np.random.randint(1, 10, size = (3, 3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis = 0), np.sum(a2, axis = 0)) # 열방향 합
print(a2.sum(axis = 1), np.sum(a2, axis = 1)) # 행방향 합

[[6 1 9]
 [7 4 9]
 [5 7 2]]
50 50
[18 12 20] [18 12 20]
[16 20 14] [16 20 14]


In [96]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis = 0))
print(np.cumsum(a2, axis = 1))

[[6 1 9]
 [7 4 9]
 [5 7 2]]
[ 6  7 16 23 27 36 41 48 50]
[[ 6  1  9]
 [13  5 18]
 [18 12 20]]
[[ 6  7 16]
 [ 7 11 20]
 [ 5 12 14]]


In [97]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis = 0))
print(np.prod(a2, axis = 1))

[[6 1 9]
 [7 4 9]
 [5 7 2]]
952560
[210  28 162]
[ 54 252  70]


In [98]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis = 0))
print(np.cumprod(a2, axis = 1))

[[6 1 9]
 [7 4 9]
 [5 7 2]]
[     6      6     54    378   1512  13608  68040 476280 952560]
[[  6   1   9]
 [ 42   4  81]
 [210  28 162]]
[[  6   6  54]
 [  7  28 252]
 [  5  35  70]]


In [99]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[6 1 9]
 [7 4 9]
 [5 7 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[16 16 16]
 [20 20 20]
 [14 14 14]]
[[16 16 16]
 [20 20 20]
 [14 14 14]]


In [101]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis = 0))
print(np.mean(a2, axis = 1))

[[6 1 9]
 [7 4 9]
 [5 7 2]]
5.555555555555555
[6.         4.         6.66666667]
[5.33333333 6.66666667 4.66666667]


In [102]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis = 0))
print(np.std(a2, axis = 1))

[[6 1 9]
 [7 4 9]
 [5 7 2]]
2.671292284482513
[0.81649658 2.44948974 3.29983165]
[3.29983165 2.05480467 2.05480467]


In [103]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis = 0))
print(np.var(a2, axis = 1))

[[6 1 9]
 [7 4 9]
 [5 7 2]]
7.135802469135803
[ 0.66666667  6.         10.88888889]
[10.88888889  4.22222222  4.22222222]


In [104]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis = 0))
print(np.min(a2, axis = 1))

[[6 1 9]
 [7 4 9]
 [5 7 2]]
1
[5 1 2]
[1 4 2]


In [105]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis = 0))
print(np.max(a2, axis = 1))

[[6 1 9]
 [7 4 9]
 [5 7 2]]
9
[7 7 9]
[9 9 7]


In [106]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis = 0))
print(np.argmin(a2, axis = 1))

[[6 1 9]
 [7 4 9]
 [5 7 2]]
1
[2 0 2]
[1 1 2]


In [107]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis = 0))
print(np.argmax(a2, axis = 1))

[[6 1 9]
 [7 4 9]
 [5 7 2]]
2
[1 2 0]
[2 2 1]


In [108]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis = 0))
print(np.median(a2, axis = 1))

[[6 1 9]
 [7 4 9]
 [5 7 2]]
6.0
[6. 4. 9.]
[6. 7. 5.]


In [111]:
a1 = np.arange(1, 13)
print(a1)
print(np.percentile(a1, [30, 50, 80], interpolation = "linear"))
print(np.percentile(a1, [30, 50, 80], interpolation = "lower"))
print(np.percentile(a1, [30, 50, 80], interpolation = "higher"))
print(np.percentile(a1, [30, 50, 80], interpolation = "nearest"))
print(np.percentile(a1, [30, 50, 80], interpolation = "midpoint"))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[4.3 6.5 9.8]
[4 6 9]
[ 5  7 10]
[ 4  7 10]
[4.5 6.5 9.5]


In [112]:
a2 = np.array([[10, 7, 5], [3, 2, 1]])
print(a2)

[[10  7  5]
 [ 3  2  1]]


In [115]:
print(np.percentile(a2, 50))
print(np.percentile(a2, 50, axis = 0))
print(np.percentile(a2, 50, axis = 1))

4.0
[6.5 4.5 3. ]
[7. 2.]


In [117]:
# any()

a2 = np.array([[False, False, False],
               [True, True, True],
               [False, True, True]])
print(np.any(a2))
print(np.any(a2, axis = 0))
print(np.any(a2, axis = 1))

True
[ True  True  True]
[False  True  True]


In [118]:
# all()

print(np.all(a2))
print(np.all(a2, axis = 0))
print(np.all(a2, axis = 1))

False
[False False False]
[False  True False]


In [119]:
# 비교연산

a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [120]:
# 배열 정렬
# np.sort(array) : 정렬된 배열의 복사본 생성, 원본 배열의 변경 없음
# array.sort() : 원본 배열의 값이 변경됨

a1 = np.random.randint(1, 10, size = 10)
print(a1)

[3 1 7 7 6 8 1 2 2 6]


In [121]:
print(np.sort(a1))
print(a1)
print(a1.sort())
print(a1)

[1 1 2 2 3 6 6 7 7 8]
[3 1 7 7 6 8 1 2 2 6]
None
[1 1 2 2 3 6 6 7 7 8]


In [123]:
# 부분정렬 
# partition(array, k) : 배열에서 k개의 작은 값을 선택하여 왼쪽에 배치
# -k : k개의 큰 값을 오른쪽에 배치

a1 = np.random.randint(1, 10, size = 10)
print(a1)
print(np.partition(a1, 3))
print(np.partition(a1, -3))

[9 1 3 9 1 1 2 1 1 6]
[1 1 1 1 1 3 2 6 9 9]
[1 1 3 1 1 1 2 6 9 9]


In [124]:
# 배열 입출력

a2 = np.random.randint(1, 10, size = (5, 5))
print(a2)
np.save("a", a2)

[[7 8 7 2 1]
 [6 6 2 1 7]
 [2 6 6 9 6]
 [8 7 5 6 3]
 [6 7 1 1 8]]


In [125]:
ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 0CF3-A853

 C:\Users\wnsgm\Documents\준희\Python\Work\datamining 디렉터리

2022-03-25  오후 06:45    <DIR>          .
2022-03-25  오후 06:45    <DIR>          ..
2022-03-25  오후 04:48    <DIR>          .ipynb_checkpoints
2022-03-25  오후 06:45               228 a.npy
2022-03-25  오후 06:45            92,772 NumPy1.ipynb
2022-03-21  오후 02:17           120,056 Pandas.ipynb
               3개 파일             213,056 바이트
               3개 디렉터리  399,454,216,192 바이트 남음


---

# 참고문헌

* NumPy, https://numpy.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly